dbt_project:
  outputs:
    dev:
      type: duckdb
      path: "md:my_db?motherduck_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFraXJhQHNhbmdvLXRlY2guY29tIiwic2Vzc2lvbiI6ImFraXJhLnNhbmdvLXRlY2guY29tIiwicGF0IjoiN28wZmdtTEo3REFqV0VnWjV4TVVwUGhUREdhMVRZaGRiMUpYeExGYW9vSSIsInVzZXJJZCI6Ijc2ZmQ2YTFlLWE2NGEtNDhhNi1iMGE0LWI4MjFlODRmZWQyOCIsImlzcyI6Im1kX3BhdCIsImlhdCI6MTcyOTgyOTk1NH0.Z1FO2MLAiYD0uNg5aVOu75NyIDy5ZbfM8Tw9yGBxxRw"
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
