# version: 2
# 
# models:
#   - name: goods
#     description: "商品情報テーブル"
#     columns:
#       - name: goodscode1
#         description: "商品コード1"
#         data_tests:
#           - not_null       # goodscode1がNULLでないことをチェック
#       - name: goodscode2
#         description: "商品コード2"
#         data_tests:
#           - not_null       # goodscode2がNULLでないことをチェック
#       - name: goodstype1
#         description: "商品定義1"
#       - name: goodstype2
#         description: "商品定義2"
#       - name: goodstype3
#         description: "商品定義3"
#       - name: goodstype4
#         description: "商品定義4"
# 
#     data_tests:
#       - unique:
#           column_name: "(goodscode1 || '-' || goodscode2)"
